# Supabase configuration (project linked via CLI)
project_id = "nbeiexnlnmpdbdfdqrjr"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]

[db]
port = 54322
major_version = 15

[studio]
enabled = true
port = 54323


[auth]
enabled = true
site_url = "http://localhost:5177"
additional_redirect_urls = ["http://localhost:5175", "https://*"]
jwt_expiry = 3600
enable_signup = true
